In [ ]:
1. Huggingface Hub(Finetuning chapter will discuss this HF in detail)
2. OpenAI SDK(Lang-chain)
2. Gemini SDK(Lang-chain)

HF
Langchain

In [1]:
import os
os.environ["GOOGLE_API_KEY"] =os.getenv("GOOGLE_API_KEY")
os.environ["HF_TOKEN"] = os.getenv("HF_TOKEN")
os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")

In [2]:
from sentence_transformers import SentenceTransformer

e:\Full Stack Gen AI and Agentic AI Bootcamp\env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
open_source_embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

In [4]:
text = "machine"

In [5]:
embedding =open_source_embedding_model.encode(text)

In [6]:
embedding

array([-7.21354410e-02,  2.84874551e-02, -1.17706126e-02,  1.98008772e-02,
       -4.34783362e-02, -3.14590000e-02,  1.49604762e-02,  2.88986880e-03,
        3.24487640e-03, -3.39518748e-02,  1.04992324e-02, -1.02071995e-02,
        7.77680576e-02, -7.65563995e-02, -1.39956153e-03, -2.10193056e-03,
        1.71924122e-02, -6.33648485e-02, -2.81336661e-02, -5.86969182e-02,
       -3.29725407e-02,  1.02291368e-02, -6.45695478e-02,  1.98799595e-02,
       -1.06031718e-02,  1.04793400e-01, -3.81070636e-02,  5.03518507e-02,
        2.06003450e-02, -1.30085513e-01, -2.18260307e-02,  4.07632394e-03,
        6.23156593e-05,  2.95541510e-02,  3.27022821e-02, -1.54474946e-02,
        3.09898946e-02, -3.76024656e-02,  1.37064802e-02, -5.00646792e-02,
        2.30320916e-02, -7.93177933e-02, -8.26479936e-06, -1.97606366e-02,
        7.49427527e-02,  1.02477886e-01,  6.01520436e-03, -3.98588106e-02,
        5.47021888e-02,  3.11047509e-02, -1.16405949e-01, -7.04230592e-02,
        6.45304993e-02,  

In [7]:
len(embedding)

384

In [8]:
embedding.shape

(384,)

In [9]:
sentence = "How to reduce heart disease risk?"

In [10]:
embedding =open_source_embedding_model.encode(sentence)

In [11]:
embedding.shape

(384,)

In [12]:
paragraph = """
Machine learning is a field of artificial intelligence that focuses on building systems 
that learn from data. It is widely used in applications like recommendation systems, 
image recognition, and natural language processing.
"""

In [13]:
embedding = open_source_embedding_model.encode(paragraph)

In [14]:
embedding.shape

(384,)

In [15]:
embedding

array([-2.78186798e-02, -6.40660478e-03,  3.68497372e-02,  2.21404689e-03,
        2.55084336e-02,  1.34023083e-02,  6.45566639e-03, -3.05500831e-02,
       -6.01915084e-02, -2.28518229e-02, -7.05490112e-02,  1.97643787e-02,
        5.54116145e-02, -3.38736176e-02, -9.74510424e-03,  4.72750515e-02,
       -1.58115178e-02, -1.64723676e-02, -6.00375310e-02, -7.00236335e-02,
        2.54246928e-02, -5.45074092e-03, -7.51983076e-02,  1.57804154e-02,
       -1.62698328e-02,  5.30246682e-02,  6.29331246e-02,  1.47748403e-02,
       -1.32339094e-02,  5.44597255e-03,  2.14248747e-02, -3.44793163e-02,
        1.16899069e-02,  4.35766652e-02, -4.42826711e-02,  5.05335182e-02,
       -2.66971309e-02,  5.36211208e-03,  7.96867721e-03, -1.89669728e-02,
       -6.25875518e-02, -7.47380704e-02,  6.55541150e-03, -6.77178428e-03,
        1.26145527e-01,  1.28760204e-01, -7.31318668e-02, -9.79881287e-02,
        8.16384214e-04,  1.73747130e-02, -1.05541214e-01,  1.18358172e-02,
       -1.23240715e-02,  

In [15]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings

In [16]:
google_embeddings_model = GoogleGenerativeAIEmbeddings(model="gemini-embedding-001")

In [17]:
embedding = google_embeddings_model.embed_query("What is the capital of France?")

In [18]:
len(embedding)

3072

In [19]:
#from langchain_openai import OpenAIEmbeddings

In [20]:
#openai_embeddings_model=OpenAIEmbeddings(model="text-embedding-3-large")

In [21]:
#embedding = openai_embeddings_model.embed_query("What is the capital of France?")

In [22]:
#len(embedding)

In [23]:
#openai_embeddings_small_model=OpenAIEmbeddings(model="text-embedding-3-small")

In [24]:
#embedding = openai_embeddings_small_model.embed_query("What is the capital of France?")

In [25]:
#len(embedding)

TEXT

IMAGE?

ViT(vision transformer) and CLIP(contrastive language-image pretraining) are two popular transformer-based models used for image processing tasks.

In [27]:
from transformers import CLIPModel, CLIPProcessor

In [28]:
from PIL import Image

In [29]:
image = Image.open("E:\Full Stack Gen AI and Agentic AI Bootcamp\SOTA-Transformer-Embedding-Methods\image\Krishna Chaitanya.png")

In [30]:
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
e:\Full Stack Gen AI and Agentic AI Bootcamp\env\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\bkcha\.cache\huggingface\hub\models--openai--clip-vit-base-patch32. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to ac

In [31]:
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


In [ ]:
inputs =processor(images=image, return_tensors="pt")

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


In [33]:
import torch

In [34]:
# Get embedding
with torch.no_grad():
    image_embedding = model.get_image_features(**inputs)

In [35]:
image_embedding

tensor([[ 3.0546e-01, -1.0004e-01, -9.2446e-02,  2.7045e-01,  1.3248e-02,
          1.1385e-01, -1.0805e-01,  6.1159e-01,  1.0394e+00, -1.1512e-01,
          2.3789e-01, -2.9103e-01, -4.0881e-01, -5.8782e-01, -2.4393e-01,
         -2.9277e-01,  1.8875e+00, -3.0651e-02, -1.8928e-01, -1.9131e-01,
          5.8366e-01,  2.6339e-01,  4.3340e-01, -9.4275e-02,  3.7807e-03,
          2.1138e-01,  1.6022e-02,  1.1993e-01,  9.6098e-02,  7.9905e-02,
          1.6504e-01,  1.5293e-01, -5.8806e-01,  4.2865e-01,  5.7248e-01,
          1.9374e-01, -1.4295e-01, -1.2487e-01,  2.4937e-01,  8.2490e-02,
         -1.5802e-01, -1.5718e-01,  3.5239e-01, -3.2216e-01, -6.4053e-02,
          3.6200e+00, -1.3335e-01,  2.8953e-01,  1.8851e-01,  5.4432e-01,
         -1.5453e-01,  1.4454e-01,  8.0476e-02, -1.0411e-01, -2.2346e-02,
          4.4468e-02,  3.2395e-01,  3.2204e-01,  5.3954e-01,  4.9426e-01,
          1.4964e-01, -3.1802e-01,  3.8865e-01,  2.0334e-01,  1.7601e-01,
         -5.1554e-01,  9.4326e-02,  8.

In [36]:
len(image_embedding[0])

512

## Semantic Search (Similarity Search)

1. Dot Product
2. Cosine Sim
3. Eculidean Distance(L2)

In [37]:
def dot_product(a, b):
    return np.dot(a, b)

In [38]:
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [39]:
def euclidean_distance(a, b):
    a = np.array(a)
    b = np.array(b)
    return np.linalg.norm(a - b)

In [40]:
print("=== Cosine Similarity (Higher is better) ===")
print("Range: -1 to 1")

print("\n=== Dot Product (Higher is better) ===")
print("Range: -∞ to +∞ (depends on vector magnitude)")

print("\n=== Euclidean Distance (Lower is better) ===")
print("Range: 0 to +∞")

=== Cosine Similarity (Higher is better) ===
Range: -1 to 1

=== Dot Product (Higher is better) ===
Range: -∞ to +∞ (depends on vector magnitude)

=== Euclidean Distance (Lower is better) ===
Range: 0 to +∞


In [50]:
query = "How to reduce heart disease risk?"

In [42]:
documents = [
    "Eating fiber reduces heart risk.",
    "Fruits and vegetables lower cardiovascular disease chances.",
    "Buying a new car improves driving comfort.",
    "Regular exercise improves heart health."
]

In [52]:
query_embedding = google_embeddings_model.embed_query(query)

In [44]:
doc_embeddings = google_embeddings_model.embed_documents(documents)

In [45]:
len(doc_embeddings)

4

In [46]:
len(doc_embeddings[0])

3072

In [47]:
import numpy as np

In [48]:
results = []

In [53]:
for doc, doc_emb in zip(documents, doc_embeddings):
    results.append({
        "query": query,
        "document": doc,
        "cosine": cosine_similarity(query_embedding, doc_emb),
        "dot_product": dot_product(query_embedding, doc_emb),
        "euclidean": euclidean_distance(query_embedding, doc_emb)
    })

In [54]:
results

[{'query': 'How to reduce heart disease risk?',
  'document': 'Eating fiber reduces heart risk.',
  'cosine': 0.7395238839381588,
  'dot_product': 0.739523906997596,
  'euclidean': 0.721770218537545},
 {'query': 'How to reduce heart disease risk?',
  'document': 'Fruits and vegetables lower cardiovascular disease chances.',
  'cosine': 0.7132289221700369,
  'dot_product': 0.7132289415495634,
  'euclidean': 0.7573256705301548},
 {'query': 'How to reduce heart disease risk?',
  'document': 'Buying a new car improves driving comfort.',
  'cosine': 0.5761824193919591,
  'dot_product': 0.5761824550973115,
  'euclidean': 0.9206710670717551},
 {'query': 'How to reduce heart disease risk?',
  'document': 'Regular exercise improves heart health.',
  'cosine': 0.7141669909372164,
  'dot_product': 0.7141670824821801,
  'euclidean': 0.7560860343930161}]

# Keyword Search

In [55]:
documents

['Eating fiber reduces heart risk.',
 'Fruits and vegetables lower cardiovascular disease chances.',
 'Buying a new car improves driving comfort.',
 'Regular exercise improves heart health.']

In [56]:
query

'How to reduce heart disease risk?'

In [57]:
from collections import Counter

In [58]:
query.lower().replace("?", "").split()

['how', 'to', 'reduce', 'heart', 'disease', 'risk']

In [59]:
query_words = query.lower().replace("?", "").split()

In [60]:
documents[0]

'Eating fiber reduces heart risk.'

In [61]:
doc_words = documents[0].lower().replace(".", "").split()

In [62]:
doc_words

['eating', 'fiber', 'reduces', 'heart', 'risk']

In [63]:
doc_count = Counter(doc_words)

In [64]:
doc_count

Counter({'eating': 1, 'fiber': 1, 'reduces': 1, 'heart': 1, 'risk': 1})

In [65]:
for word in query_words:
    print(f"{word}: {doc_count[word]}")

how: 0
to: 0
reduce: 0
heart: 1
disease: 0
risk: 1


In [66]:
score = sum(doc_count[word] for word in query_words) 

# Score = number of matching words

In [67]:
score

2

In [68]:
def keyword_search(query, documents):
    query_words = query.lower().replace("?", "").split()
    results = []

    for doc in documents:
        doc_words = doc.lower().replace(".", "").split()
        doc_count = Counter(doc_words)

        score = sum(doc_count[word] for word in query_words) 
        results.append((doc, score))

    return sorted(results, key=lambda x: x[1], reverse=True)

In [69]:
keyword_results = keyword_search(query, documents)

In [70]:
keyword_results

[('Eating fiber reduces heart risk.', 2),
 ('Fruits and vegetables lower cardiovascular disease chances.', 1),
 ('Regular exercise improves heart health.', 1),
 ('Buying a new car improves driving comfort.', 0)]