In [ ]:
1. Huggingface Hub(Finetuning chapter will discuss this HF in detail)
2. OpenAI SDK(Lang-chain)
2. Gemini SDK(Lang-chain)

HF
Langchain

In [1]:
import os
os.environ["GOOGLE_API_KEY"] =os.getenv("GOOGLE_API_KEY")
os.environ["HF_TOKEN"] = os.getenv("HF_TOKEN")
os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")

In [3]:
from sentence_transformers import SentenceTransformer

e:\Full Stack Gen AI and Agentic AI Bootcamp\env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
open_source_embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

e:\Full Stack Gen AI and Agentic AI Bootcamp\env\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\bkcha\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. 

In [5]:
text = "machine"

In [6]:
embedding =open_source_embedding_model.encode(text)

In [9]:
embedding

array([-7.21354410e-02,  2.84874812e-02, -1.17706051e-02,  1.98008735e-02,
       -4.34782878e-02, -3.14589851e-02,  1.49604604e-02,  2.88983458e-03,
        3.24491435e-03, -3.39518823e-02,  1.04991766e-02, -1.02072367e-02,
        7.77680576e-02, -7.65563548e-02, -1.39953243e-03, -2.10196618e-03,
        1.71924289e-02, -6.33648038e-02, -2.81336270e-02, -5.86969554e-02,
       -3.29725742e-02,  1.02291415e-02, -6.45695105e-02,  1.98799465e-02,
       -1.06030926e-02,  1.04793422e-01, -3.81070673e-02,  5.03518432e-02,
        2.06002817e-02, -1.30085543e-01, -2.18260866e-02,  4.07640776e-03,
        6.23128799e-05,  2.95541193e-02,  3.27022783e-02, -1.54475253e-02,
        3.09899021e-02, -3.76024470e-02,  1.37064420e-02, -5.00646755e-02,
        2.30320580e-02, -7.93178007e-02, -8.28152679e-06, -1.97606031e-02,
        7.49427602e-02,  1.02477893e-01,  6.01521553e-03, -3.98588516e-02,
        5.47022372e-02,  3.11047211e-02, -1.16406001e-01, -7.04231113e-02,
        6.45304769e-02,  

In [7]:
len(embedding)

384

In [8]:
embedding.shape

(384,)

In [9]:
sentence = "How to reduce heart disease risk?"

In [10]:
embedding =open_source_embedding_model.encode(sentence)

In [11]:
embedding.shape

(384,)

In [12]:
paragraph = """
Machine learning is a field of artificial intelligence that focuses on building systems 
that learn from data. It is widely used in applications like recommendation systems, 
image recognition, and natural language processing.
"""

In [13]:
embedding = open_source_embedding_model.encode(paragraph)

In [14]:
embedding.shape

(384,)

In [15]:
embedding

array([-2.78186798e-02, -6.40660478e-03,  3.68497372e-02,  2.21404689e-03,
        2.55084336e-02,  1.34023083e-02,  6.45566639e-03, -3.05500831e-02,
       -6.01915084e-02, -2.28518229e-02, -7.05490112e-02,  1.97643787e-02,
        5.54116145e-02, -3.38736176e-02, -9.74510424e-03,  4.72750515e-02,
       -1.58115178e-02, -1.64723676e-02, -6.00375310e-02, -7.00236335e-02,
        2.54246928e-02, -5.45074092e-03, -7.51983076e-02,  1.57804154e-02,
       -1.62698328e-02,  5.30246682e-02,  6.29331246e-02,  1.47748403e-02,
       -1.32339094e-02,  5.44597255e-03,  2.14248747e-02, -3.44793163e-02,
        1.16899069e-02,  4.35766652e-02, -4.42826711e-02,  5.05335182e-02,
       -2.66971309e-02,  5.36211208e-03,  7.96867721e-03, -1.89669728e-02,
       -6.25875518e-02, -7.47380704e-02,  6.55541150e-03, -6.77178428e-03,
        1.26145527e-01,  1.28760204e-01, -7.31318668e-02, -9.79881287e-02,
        8.16384214e-04,  1.73747130e-02, -1.05541214e-01,  1.18358172e-02,
       -1.23240715e-02,  

In [19]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings

In [20]:
google_embeddings_model = GoogleGenerativeAIEmbeddings(model="gemini-embedding-001")

In [21]:
embedding = google_embeddings_model.embed_query("What is the capital of France?")

In [22]:
len(embedding)

3072

In [16]:
from langchain_openai import OpenAIEmbeddings

In [17]:
openai_embeddings_model=OpenAIEmbeddings(model="text-embedding-3-large")

In [18]:
embedding = openai_embeddings_model.embed_query("What is the capital of France?")

RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

In [27]:
len(embedding)

3072

In [28]:
openai_embeddings_small_model=OpenAIEmbeddings(model="text-embedding-3-small")

In [30]:
embedding = openai_embeddings_small_model.embed_query("What is the capital of France?")

In [31]:
len(embedding)

1536

In [ ]:
TEXT

IMAGE?

ViT(vision transformer) and CLIP(contrastive language-image pretraining) are two popular transformer-based models used for image processing tasks.

In [23]:
from transformers import CLIPModel, CLIPProcessor

In [24]:
from PIL import Image

In [26]:
image = Image.open("E:\Full Stack Gen AI and Agentic AI Bootcamp\SOTA-Transformer-Embedding-Methods\image\Krishna Chaitanya.png")

In [39]:
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.


In [38]:
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")

In [41]:
inputs =processor(images=image, return_tensors="pt")

In [44]:
import torch

In [45]:
# Get embedding
with torch.no_grad():
    image_embedding = model.get_image_features(**inputs)

In [46]:
image_embedding

tensor([[ 3.0268e-01,  4.7514e-02, -1.0944e-01,  3.7604e-01, -3.3138e-01,
          1.0324e-01, -4.7890e-02,  3.5617e-01,  7.6529e-01,  5.0290e-02,
          4.5722e-01, -2.6173e-01,  3.0070e-02, -6.6185e-01, -1.8770e-01,
         -1.2801e-02,  1.8427e+00,  2.3160e-02,  8.1963e-02, -4.2190e-01,
          1.7335e+00,  1.3869e-01, -1.2739e-01, -3.0044e-01,  1.2033e-01,
          1.4199e-01, -9.9706e-04,  2.3606e-01,  2.7052e-01,  5.5268e-02,
         -3.1191e-02, -2.4044e-01, -1.8626e-01,  2.3131e-01,  2.8196e-01,
          2.7599e-01, -6.9388e-02,  1.7465e-01, -2.6055e-01, -1.2248e+00,
         -8.6463e-01, -3.5701e-02,  8.5625e-01, -4.4047e-01, -1.6610e-01,
          3.4468e+00,  1.6835e-01,  1.6050e-01,  8.8021e-02,  6.7718e-01,
         -3.8039e-01,  3.9413e-01,  5.1323e-01, -2.6127e-02, -3.4481e-01,
          7.0976e-01, -1.6183e-01,  6.1377e-02,  3.0291e-01, -1.6714e-01,
          4.8288e-01, -2.3115e-01,  1.4020e-01,  7.4183e-02, -2.1236e-01,
         -4.6074e-01, -2.6213e-01,  9.

In [48]:
len(image_embedding[0])

512

## Semantic Search (Similarity Search)

1. Dot Product
2. Cosine Sim
3. Eculidean Distance(L2)

In [49]:
def dot_product(a, b):
    return np.dot(a, b)

In [50]:
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [51]:
def euclidean_distance(a, b):
    a = np.array(a)
    b = np.array(b)
    return np.linalg.norm(a - b)

In [58]:
print("=== Cosine Similarity (Higher is better) ===")
print("Range: -1 to 1")

print("\n=== Dot Product (Higher is better) ===")
print("Range: -∞ to +∞ (depends on vector magnitude)")

print("\n=== Euclidean Distance (Lower is better) ===")
print("Range: 0 to +∞")

=== Cosine Similarity (Higher is better) ===
Range: -1 to 1

=== Dot Product (Higher is better) ===
Range: -∞ to +∞ (depends on vector magnitude)

=== Euclidean Distance (Lower is better) ===
Range: 0 to +∞


In [52]:
query = "How to reduce heart disease risk?"

In [53]:
documents = [
    "Eating fiber reduces heart risk.",
    "Fruits and vegetables lower cardiovascular disease chances.",
    "Buying a new car improves driving comfort.",
    "Regular exercise improves heart health."
]

In [64]:
query_embedding = openai_embeddings_model.embed_query(query)

In [65]:
doc_embeddings = openai_embeddings_model.embed_documents(documents)

In [66]:
len(doc_embeddings)

4

In [67]:
len(doc_embeddings[0])

3072

In [68]:
import numpy as np

In [69]:
results = []

In [70]:
for doc, doc_emb in zip(documents, doc_embeddings):
    results.append({
        "query": query,
        "document": doc,
        "cosine": cosine_similarity(query_embedding, doc_emb),
        "dot_product": dot_product(query_embedding, doc_emb),
        "euclidean": euclidean_distance(query_embedding, doc_emb)
    })

In [71]:
results

[{'query': 'How to reduce heart disease risk?',
  'document': 'Eating fiber reduces heart risk.',
  'cosine': 0.5985462508876028,
  'dot_product': 0.5986208614314315,
  'euclidean': 0.8961069525957198},
 {'query': 'How to reduce heart disease risk?',
  'document': 'Fruits and vegetables lower cardiovascular disease chances.',
  'cosine': 0.5578602807682239,
  'dot_product': 0.5577105806559395,
  'euclidean': 0.9402351589986666},
 {'query': 'How to reduce heart disease risk?',
  'document': 'Buying a new car improves driving comfort.',
  'cosine': 0.06057430919232074,
  'dot_product': 0.060568684150503316,
  'euclidean': 1.3706483553936326},
 {'query': 'How to reduce heart disease risk?',
  'document': 'Regular exercise improves heart health.',
  'cosine': 0.4914256906935539,
  'dot_product': 0.491606805490445,
  'euclidean': 1.0087238371978915}]

# Keyword Search

In [72]:
documents

['Eating fiber reduces heart risk.',
 'Fruits and vegetables lower cardiovascular disease chances.',
 'Buying a new car improves driving comfort.',
 'Regular exercise improves heart health.']

In [73]:
query

'How to reduce heart disease risk?'

In [75]:
from collections import Counter

In [77]:
query.lower().replace("?", "").split()

['how', 'to', 'reduce', 'heart', 'disease', 'risk']

In [84]:
query_words = query.lower().replace("?", "").split()

In [78]:
documents[0]

'Eating fiber reduces heart risk.'

In [79]:
doc_words = documents[0].lower().replace(".", "").split()

In [80]:
doc_words

['eating', 'fiber', 'reduces', 'heart', 'risk']

In [81]:
doc_count = Counter(doc_words)

In [82]:
doc_count

Counter({'eating': 1, 'fiber': 1, 'reduces': 1, 'heart': 1, 'risk': 1})

In [86]:
for word in query_words:
    print(f"{word}: {doc_count[word]}")

how: 0
to: 0
reduce: 0
heart: 1
disease: 0
risk: 1


In [87]:
score = sum(doc_count[word] for word in query_words) 

# Score = number of matching words

In [88]:
score

2

In [90]:
def keyword_search(query, documents):
    query_words = query.lower().replace("?", "").split()
    results = []

    for doc in documents:
        doc_words = doc.lower().replace(".", "").split()
        doc_count = Counter(doc_words)

        score = sum(doc_count[word] for word in query_words) 
        results.append((doc, score))

    return sorted(results, key=lambda x: x[1], reverse=True)

In [91]:
keyword_results = keyword_search(query, documents)

In [92]:
keyword_results

[('Eating fiber reduces heart risk.', 2),
 ('Fruits and vegetables lower cardiovascular disease chances.', 1),
 ('Regular exercise improves heart health.', 1),
 ('Buying a new car improves driving comfort.', 0)]